### PR TITLE
returned spotify url

### PR DESCRIPTION
**Pull request by exiify**

### CODE REVIEW

**Comment by Solaris9** [comment]
This gets overwritten when the track is resolved

**Comment by exiify** [comment]
> This gets overwritten when the track is resolved

Yeah, I found a workaround that I will make a PR in the erela.js repo in a few minutes

**Comment by exiify** [comment]
> This gets overwritten when the track is resolved

https://github.com/MenuDocs/erela.js/pull/106

**Comment by Strandxo** [comment]
Is this issue resolved?

**Pull request closed without merging**
